####------------------------------- Query Manupilation ------------------------------

################################### Week days Dict ##################################

days = {
    -1 : 'saturday',
    0 : 'sunday',
    1 : 'monday',
    2 : 'tuesday',
    3 : 'wednesday',
    4 : 'thursday',
    5 : 'friday',
    6 : 'saturday',
    7 : 'sunday'
}

################################### All Currency Codes Dict #########################

currency1 = {
    "albanian lek" : "ALL",
    "argentine peso" : "ARS",
    "australian dollar" : "AUD",
    "bulgarian lev" : "BGN",
    "bahraini dinar" : "BHD",
    "brazilian real" : "BRL",
    "british pound" : "GBP",
    "canadian dollar" : "CAD",
    "swiss franc" : "CHF",
    "chilean peso" : "CLP",
    "chinese yuan" : "CNY",
    "colombian peso" : "COP",
    "czech koruna" : "CZK",
    "danish krone" : "DKK",
    "euro" : "EUR",
    "pound sterling" : "GBP",
    "hong kong dollar" : "HKD",
    "hungarian forint" : "HUF",
    "indonesian rupiah" : "IDR",
    "israeli new shekel" : "ILS",
    "indian rupee" : "INR",
    "icelandic króna" : "ISK",
    "japanese yen" : "JPY",
    "korean won" : "KRW",
    "morocan dirham" : "MAD",
    "mexican peso" : "MXN",
    "mexican unidad de inversión (Udi)" : "MXV",
    "malaysian ringit" : "MYR",
    "namibian dollar" : "NAD",
    "nigerian naira" : "NGN",
    "norwegian krone" : "NOK",
    "new zealand dollar" : "NZD",
    "all other currencies" : "OTH",
    "peruvian sol" : "PEN",
    "philippine peso" : "PHP",
    "polish zloty " : "PLN",
    "romanian leu" : "RON",
    "russian ruble" : "RUB",
    "saudi riyal" : "SAR",
    "swedish krona" : "SEK",
    "singapore dollar" : "SGD",
    "thai baht" : "THB",
    "turkish lira" : "TRY",
    "new taiwan dollar" : "TWD",
    "us dollar" : "USD",
    "bolívar soberano" : "VES",
    "vietnamese dong" : "VND",
    "cfa franc (bcEaO)" : "XOF",
    "south african rand" : "ZAR",
"australia dollar":"AUD",
    "great britain pound":"GBP",
    "euro":"EUR",
    "japan yen":"JPY",
    "switzerland franc":"CHF",
    "usa dollar":"USD",
    "afghanistan afghani":"AFN",
    "albania lek":"ALL",
    "algeria dinar":"DZD",
    "angola kwanza":"AOA",
    "argentina peso":"ARS",
    "armenia dram":"AMD",
    "aruba florin":"AWG",
    "australia dollar":"AUD",
    "austria schilling":"ATS (EURO)",
    "belgium franc":"BEF (EURO)",
    "azerbaijan new manat":"AZN",
    "bahamas dollar":"BSD",
    "bahrain dinar":"BHD",
    "bangladesh taka":"BDT",
    "barbados dollar":"BBD",
    "belarus ruble":"BYR",
    "belize dollar":"BZD",
    "bermuda dollar":"BMD",
    "bhutan ngultrum":"BTN",
    "bolivia boliviano":"BOB",
    "bosnia mark":"BAM",
    "botswana pula":"BWP",
    "brazil real":"BRL",
    "great britain pound":"GBP",
    "brunei dollar":"BND",
    "bulgaria lev":"BGN",
    "burundi franc":"BIF",
    "cambodia riel":"KHR",
    "canada dollar":"CAD",
    "cape verde escudo":"CVE",
    "cayman islands dollar":"KYD",
    "chili peso":"CLP",
    "china yuan":"CNY",
    "colombia peso":"COP",
    "comoros franc":"KMF",
    "congo franc":"CDF",
    "costa rica colon":"CRC",
    "croatia kuna":"HRK",
    "cuba convertible peso":"CUC",
    "cuba peso":"CUP",
    "cyprus pound":"CYP (EURO)",
    "czech koruna":"CZK",
    "denmark krone":"DKK",
    "djibouti franc":"DJF",
    "dominican republich peso":"DOP",
    "east caribbean dollar":"XCD",
    "egypt pound":"EGP",
    "el salvador colon":"SVC",
    "estonia kroon":"EEK (EURO)",
    "ethiopia birr":"ETB",
    "euro":"EUR",
    "falkland islands pound":"FKP",
    "finland markka":"FIM (EURO)",
    "fiji dollar":"FJD",
    "gambia dalasi":"GMD",
    "georgia lari":"GEL",
    "germany mark":"DMK (EURO)",
    "ghana new cedi":"GHS",
    "gibraltar pound":"GIP",
    "greece drachma":"GRD (EURO)",
    "guatemala quetzal":"GTQ",
    "guinea franc":"GNF",
    "guyana dollar":"GYD",
    "haiti gourde":"HTG",
    "honduras lempira":"HNL",
    "hong kong dollar":"HKD",
    "hungary forint":"HUF",
    "iceland krona":"ISK",
    "indian rupees":"INR",
    "indonesia rupiah":"IDR",
    "iran riyal":"IRR",
    "iraq dinar":"IQD",
    "ireland pound":"IED (EURO)",
    "israel new shekel":"ILS",
    "italy lira":"ITL (EURO)",
    "jamaica dollar":"JMD",
    "japan yen":"JPY",
    "jordan dinar":"JOD",
    "kazakhstan tenge":"KZT",
    "kenya shilling":"KES",
    "kuwait dinar":"KWD",
    "kyrgyzstan som":"KGS",
    "laos kip":"LAK",
    "latvia lats":"LVL (EURO)",
    "lebanon pound":"LBP",
    "lesotho loti":"LSL",
    "liberia dollar":"LRD",
    "libya dinar":"LYD",
    "lithuania litas":"LTL (EURO)",
    "luxembourg franc":"LUF (EURO)",
    "macau pataca":"MOP",
    "macedonia denar":"MKD",
    "malagasy ariary":"MGA",
    "malawi kwacha":"MWK",
    "malaysia ringgit":"MYR",
    "maldives rufiyaa":"MVR",
    "malta lira":"MTL (EURO)",
    "mauritania ouguiya":"MRO",
    "mauritius rupee":"MUR",
    "mexico peso":"MXN",
    "moldova leu":"MDL",
    "mongolia tugrik":"MNT",
    "morocco dirham":"MAD",
    "mozambique new metical":"MZN",
    "myanmar kyat":"MMK",
    "nl antilles guilder":"ANG",
    "namibia dollar":"NAD",
    "nepal rupee":"NPR",
    "netherlands guilder":"NLG (EURO)",
    "new Zealand dollar":"NZD",
    "nicaragua cordoba oro":"NIO",
    "nigeria naira":"NGN",
    "north korea Won":"KPW",
    "norway kroner":"NOK",
    "oman rial":"OMR",
    "pakistan rupee":"PKR",
    "panama balboa":"PAB",
    "papua new guinea kina":"PGK",
    "paraguay guarani":"PYG",
    "peru nuevo sol":"PEN",
    "philippines peso":"PHP",
    "poland zloty":"PLN",
    "portugal escudo":"PTE (EURO)",
    "qatar riyal":"QAR",
    "romania new lei":"RON",
    "russia ruble":"RUB",
    "rwanda franc":"RWF",
    "samoa tala":"WST",
    "sao tome":"STD",
    "saudi arabia riyal":"SAR",
    "serbia dinar":"RSD",
    "seychelles rupee":"SCR",
    "sierra leone":"SLL",
    "singapore dollar":"SGD",
    "slovakia koruna":"SKK (EURO)",
    "slovenia tolar":"SIT (EURO)",
    "solomon islands dollar":"SBD",
    "somali shilling":"SOS",
    "south africa rand":"ZAR",
    "south korea Won":"KRW",
    "spain peseta":"ESP (EURO)",
    "sri lanka rupee":"LKR",
    "st helena pound":"SHP",
    "sudan pound":"SDG",
    "suriname dollar":"SRD",
    "swaziland lilangeni":"SZL",
    "sweden krona":"SEK",
    "switzerland franc":"CHF",
    "syria pound":"SYP",
    "taiwan dollar":"TWD",
    "tanzania shilling":"TZS",
    "thailand baht":"THB",
    "tonga pa'anga":"TOP",
    "tobago dollar":"TTD",
    "tunisia dinar":"TND",
    "turkish new lira":"TRY",
    "turkmenistan manat":"TMM",
    "usa dollar":"USD",
    "uganda shilling":"UGX",
    "ukraine hryvnia":"UAH",
    "uruguay peso":"UYU",
    "united arab emirates dirham":"AED",
    "uae dirham":"AED",
    "vanuatu vatu":"VUV",
    "venezuela bolivar":"VEB",
    "vietnam dong":"VND",
    "yemen riyal":"YER",
    "zambia kwacha":"ZMK",
    "zimbabwe dollar":"ZWD"
}

chatbot = ['shut up','nothing','nowhere','keep quiet','no','exit','quit','ok','okay']

################################### Query replace 1 ##################################

def qReplace(query):
    ques = ["what", "what's", "tell me", "is", "in", "the", "alfred", "about", "of", "open", "close", "to", "into", "where", "are", 'we', 'who', 'play', 'why', 'when', ' ', 'translate', 'elephant', 'alford', 'orphan', 'afraid', 'alpha']
    ak = []
    list = query.split()
    for i in list:
        if i not in ques:
            ak.append(i)
    output = ''
    for j in ak:
        output+=str(j)+' '
    return output

################################### Query replace 2 ##################################

def wReplace(query):
    wake_up = ['all friend', 'elephant', 'at friend', 'alford', 'orphan', 'afraid', 'alpha', 'albert']
    text = query
    list = query.split()
    for i in list:
        if i in wake_up:
            text = text.replace(i, "alfred")
    return text

####------------------------------- End ----------------------------------------------